version: 2
jobs:
  lint-check:
    docker:
      - image: circleci/node:6.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Lint Typescript files
          command: npm run lint:check
  format-check:
    docker:
      - image: circleci/node:6.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Check code formatting using prettier
          command: npm run format:check
  build:
    docker:
      - image: circleci/node:6.16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build functions using Typescript compiler
          command: npm run build
workflows:
  version: 2
  check-functions:
    jobs:
      - lint-check
      - build